version: "3.9"

volumes:
  database: {}

services:
  db:
    image: postgres:alpine
    container_name: saerix-postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - ./.env
  backend:
    container_name: saerix-backend
    build: ./app
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  frontend:
    container_name: saerix-frontend
    build: ./frontend
    volumes:
      - ./frontend:/src
    ports:
      - "3000:3000"
    depends_on:
      - backend