# Generated by Django 3.1.7 on 2021-05-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationimage',
            name='filesize',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
