# Generated by Django 3.1.7 on 2021-05-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_commentary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentary',
            table='Commentaries',
        ),
        migrations.AlterModelTable(
            name='publication',
            table='Publications',
        ),
        migrations.AlterModelTable(
            name='publicationimage',
            table='Images',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tags',
        ),
    ]
