# Generated by Django 3.1.7 on 2021-05-10 13:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210510_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentariesDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('publication', models.CharField(max_length=50)),
                ('text', ckeditor.fields.RichTextField(max_length=5000)),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Commentaries deleted',
                'db_table': 'CommentariesDeleted',
            },
        ),
        migrations.CreateModel(
            name='TagsDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tags deleted',
                'db_table': 'TagsDeleted',
            },
        ),
    ]
