# Generated by Django 3.1.7 on 2021-05-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_commentariesdeleted_tagsdeleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagsDeleted',
        ),
    ]
