# Generated by Django 3.1.7 on 2021-05-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Articles',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='Feedbacks',
        ),
    ]
