# Generated by Django 3.1.7 on 2021-05-10 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20210510_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbacksDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(0, 'Dislike'), (1, 'Like')], default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedbacks_deleted', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedbacks_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FeedbacksDeleted',
            },
        ),
        migrations.CreateModel(
            name='ArticlesDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=5000)),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticlesDeleted',
            },
        ),
    ]
