# Generated by Django 3.1.7 on 2021-04-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210426_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='articles.article'),
        ),
    ]
