# Generated by Django 3.1.7 on 2021-05-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlesdeleted_feedbacksdeleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesdeleted',
            options={'verbose_name': 'Articles deleted'},
        ),
        migrations.AlterModelOptions(
            name='feedbacksdeleted',
            options={'verbose_name': 'Feedbacks deleted'},
        ),
    ]
