# Generated by Django 3.1.7 on 2021-05-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210510_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesdeleted',
            options={'verbose_name_plural': 'Articles deleted'},
        ),
        migrations.AlterModelOptions(
            name='feedbacksdeleted',
            options={'verbose_name_plural': 'Feedbacks deleted'},
        ),
    ]
