# Generated by Django 3.1.7 on 2021-05-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210510_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesdeleted',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedbacksdeleted',
            name='article',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedbacksdeleted',
            name='user',
            field=models.IntegerField(),
        ),
    ]
